# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "8728d27e61876f727a7bba18edeb4e54329c0770"

[[deps.ReadWriteFind]]
git-tree-sha1 = "a11abcee202164526e8bf11dc3227f48be775886"
repo-rev = "main"
repo-url = "https://github.com/runtosolve/ReadWriteFind.jl.git"
uuid = "6e1ff3fe-52ba-4718-9baa-43b124cc059a"
version = "0.1.0"
